### ISSUE TITLE
Installation issues on `R 4.0` and `R 3.6`

### ISSUE THREAD

**Issue by IndrajeetPatil** [andrjohns/QuickJSR#45]
Hi, thanks for the great package.

Our CI builds on R 3.6 are [failing](https://github.com/easystats/modelbased/actions/runs/9328926165/job/25680713253) because compilation seems to fail for this R version:

```r
  ../inst/include/quickjsr/JSValue_to_SEXP.hpp:72:37: note: candidate: ‘quickjsr::JSValue_to_SEXP_vector(JSContext*, const JSValue&)::<lambda(int&&)>’
     72 |                                     [len](auto&& vec) { return vec.size() == len; });
        |                                     ^
  ../inst/include/quickjsr/JSValue_to_SEXP.hpp:72:37: note:   no known conversion for argument 1 from ‘std::vector<double>’ to ‘int&&’
  make: *** [/opt/R/3.6.3/lib/R/etc/Makeconf:177: quickjsr.o] Error 1
  ERROR: compilation failed for package ‘QuickJSR’
  * removing ‘/tmp/Rtmpg2EnHZ/pkg-lib12f411d6546/QuickJSR’
  ```
  
  Is this expected? If yes, can you please set the minimum needed R version in `DESCRIPTION`? Thanks.

**Comment by IndrajeetPatil** [comment]
Actually, it also [fails on R 4.0](https://github.com/easystats/modelbased/actions/runs/9328926165/job/25680713212).

**Comment by andrjohns** [comment]
It looks like the package is being compiled using C++11, while it needs c++14 features:

```
  g++ -std=gnu++11 -I"/opt/R/3.6.3/lib/R/include" -DNDEBUG -I"../inst/include/" -I"../inst/include/quickjs" -D_GNU_SOURCE -DCONFIG_BIGNUM -DCONFIG_VERSION=\"2024-01-13\"  -I/usr/local/include  -fpic  -g -O2  -Wall -pedantic -c quickjsr.cpp -o quickjsr.o
  In file included from ../inst/include/quickjsr/JSValue_to_Cpp.hpp:4,
                   from ../inst/include/quickjsr/JSValue_to_SEXP.hpp:6,
                   from ../inst/include/quickjsr/SEXP_to_JSValue.hpp:5,
                   from ../inst/include/quickjsr.hpp:4,
                   from quickjsr.cpp:4:
  ../inst/include/quickjsr/type_traits.hpp:15:32: error: ‘decay_t’ in namespace ‘std’ does not name a template type; did you mean ‘decay’?
     15 |     using type = typename std::decay_t<T>;
        |                                ^~~~~~~
        |                                decay
```

I don't set a c++ standard in the package, since CRAN gives a NOTE for anything other than the default c++17

**Comment by andrjohns** [comment]
I'll have a look at what would need to change to support c++11, and if it's not too much then I'll update

**Comment by andrjohns** [comment]
@IndrajeetPatil Backwards compatibility fixed, I'll submit an update to CRAN in a week or two

**Comment by IndrajeetPatil** [comment]
Thanks a lot for the quick fix! 🙌
